stockfish_path: "C:\\Users\\diogo\\Repositorios\\MeckingLite\\engines\\stockfish\\stockfish\\stockfish.exe"
phases:
  v1_depth6:
    depth: 6
    positions: 20000
  v2_depth12:
    depth: 12
    positions: 20000
output_data_dir: "data"

# Treino supervisionado (opcional; pode ficar no root)
batch_size: 16
history_size: 4
mode: "top3"
lr: 0.001
epochs: 10
use_heuristics: true